name: flutter_golaundku
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5
  supabase_flutter: ^2.12.2
  bcrypt: ^1.2.0
  uuid: ^4.5.3
  intl: ^0.20.2
  fl_chart: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/golaundku_icons.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: '#ffffff' # You can use a color or image for the background
  adaptive_icon_foreground: 'assets/images/golaundku_icons.png' # For adaptive icons on Android
  web:
    generate: true
    image_path: 'assets/images/golaundku_icons.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/images/golaundku_icons.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/images/golaundku_icons.png'

